"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import environ
from datetime import timedelta
from pathlib import Path


# DEBUG defaults to False: a deployment that forgets its .env should fail
# closed, serving no tracebacks and no MEDIA_ROOT, rather than come up as a
# debug server. Development sets DEBUG=True in .env explicitly.
env = environ.Env(
    DEBUG=(bool, False),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])

# Everything below is off in development, where the dashboard and the phones
# talk to this server over plain HTTP on the school LAN. Turning them on
# unconditionally would make the API unreachable from both.
if not DEBUG:
    # Behind a reverse proxy terminating TLS, so trust its protocol header.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    # One year, after the shorter values have been proven in production.
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # The API answers with JWTs, not cookies, but /admin/ uses both.
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'accounts',
    'attendance',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # No default throttle: every other route already needs a token, and the
    # phones poll `ohin` freely. Only the routes that accept a password from
    # an anonymous caller opt in, by scope.
    'DEFAULT_THROTTLE_RATES': {
        'login': env('THROTTLE_LOGIN', default='20/min'),
    },
}

# The school shares one public IP, so a rate here is counted across every
# teacher on the wifi, not per person -- hence a generous default and an .env
# override, so a morning that locks people out can be fixed without a deploy.
# Login is the only anonymous password endpoint; the rest need a token first.

SIMPLE_JWT = {
    # The app refreshes on almost every open anyway -- a teacher punches a few
    # times a day and closes it -- so a short access token costs no round trips
    # the client was not already making, and keeps the window small for a
    # leaked token or a logout that has not taken effect yet.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    # With rotation below, this is an idle timeout, not a re-login deadline: a
    # teacher who punches on any weekday never logs in again, while a device
    # left untouched through the long break has to authenticate once more.
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    # Each refresh returns a new refresh token and blacklists the old one, so a
    # stolen token stops working as soon as the real device refreshes.
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://192.168.0.63:3000",
    "http://10.214.94.41:3000",
    "http://10.214.94.41:3001",
    "http://10.74.33.41:3000",
    "http://10.101.196.41:3000",
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE'),
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# Django's own validators, subclassed in `accounts.validators` so they refuse
# a password in Tetun. The rules are untouched -- only the wording, because
# validate_password was the one place this API answered in English, and it did
# so exactly where someone is being told what to fix.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'accounts.validators.HanesanDadusValidator',
    },
    {
        'NAME': 'accounts.validators.TamanMinimuValidator',
    },
    {
        'NAME': 'accounts.validators.PasswordKomunValidator',
    },
    {
        'NAME': 'accounts.validators.NumeruDeitValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dili'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Uploaded files: teacher photos and the check in / check out punch photos.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Location evidence
# Coordinates of ETI-Dili (Fomento II, Comoro), read on site. A punch further
# than ESKOLA_RAIU_METRU from this point is refused: the teacher has to be at
# the school to check in or out.

ESKOLA_LATITUDE = env.float('ESKOLA_LATITUDE', default=-8.552336)
ESKOLA_LONGITUDE = env.float('ESKOLA_LONGITUDE', default=125.541603)
ESKOLA_RAIU_METRU = env.float('ESKOLA_RAIU_METRU', default=100.0)

# Escape hatch: set to False in .env to go back to recording out-of-radius
# punches with `iha_eskola=False` instead of refusing them, without a deploy.
ESKOLA_OBRIGA_FATIN = env.bool('ESKOLA_OBRIGA_FATIN', default=True)


# Logging
# The views log a warning for every deletion, password reset and password
# change -- who did it, to whom, and how many sessions it closed. Without a
# configuration those lines went to the console and died with the process,
# which is no use at all for the one thing they exist to answer: "who removed
# this teacher's year of attendance?" They now also go to a rotating file.

# `env.path` returns django-environ's own Path type, which has no mkdir --
# take the string and keep pathlib.
LOG_DIR = Path(env.str('LOG_DIR', default=str(BASE_DIR / 'logs')))
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'auditu': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'auditu',
        },
        'auditu': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'auditu.log',
            # ~50 MB of history in total, which at this school's volume is
            # years -- the audit trail should outlive the incident it explains.
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 10,
            'formatter': 'auditu',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'accounts': {
            'handlers': ['console', 'auditu'],
            'level': 'INFO',
            'propagate': False,
        },
        'attendance': {
            'handlers': ['console', 'auditu'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
