# Generated by Django 6.0.7 on 2026-08-31 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_marka_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prezensa',
            name='rejeisaun_motivu',
            field=models.CharField(blank=True, choices=[('FOTO_FALSU', 'Foto falsu'), ('DISTANSIA_DOOK', 'Distánsia dook liu husi eskola')], max_length=20, verbose_name='motivu rejeisaun'),
        ),
        migrations.AddField(
            model_name='prezensa',
            name='rejeisaun_obs',
            field=models.TextField(blank=True, verbose_name='observasaun rejeisaun'),
        ),
        migrations.AddField(
            model_name='prezensa',
            name='rejeita_husi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prezensa_rejeitadu', to=settings.AUTH_USER_MODEL, verbose_name='rejeita husi'),
        ),
        migrations.AddField(
            model_name='prezensa',
            name='rejeita_iha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rejeita iha'),
        ),
    ]
