# Generated by Django 6.0.7 on 2026-08-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_prezensa_rejeisaun_motivu_prezensa_rejeisaun_obs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prezensa',
            name='rejeisaun_motivu',
            field=models.CharField(blank=True, choices=[('FOTO_FALSU', 'Foto falsu'), ('DISTANSIA_DOOK', 'Distánsia dook liu husi eskola'), ('HOTU_HOTU', 'Hotu-hotu')], max_length=20, verbose_name='motivu rejeisaun'),
        ),
    ]
