# Generated by Django 6.0.7 on 2026-09-01 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_prezensa_rejeisaun_motivu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prezensa',
            old_name='rejeisaun_motivu',
            new_name='rejeita_motivu',
        ),
        migrations.RenameField(
            model_name='prezensa',
            old_name='rejeisaun_obs',
            new_name='rejeita_obs',
        ),
    ]
