# Generated by Django 6.0.7 on 2026-09-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_rename_rejeisaun_motivu_prezensa_rejeita_motivu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prezensa',
            name='rejeita_motivu',
            field=models.CharField(blank=True, choices=[('FOTO_FALSU', 'Foto falsu'), ('DISTANSIA_DOOK', 'Distánsia dook liu husi eskola'), ('HOTU_HOTU', 'Hotu-hotu')], max_length=20, verbose_name='motivu rejeita'),
        ),
        migrations.AlterField(
            model_name='prezensa',
            name='rejeita_obs',
            field=models.TextField(blank=True, verbose_name='observasaun rejeita'),
        ),
    ]
